version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: vacancies_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build: .
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: vacancies_db
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db

volumes:
  db_data:
